# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af2a0b1a13e022c13d35082ddf860755a6ac6d5f307fb4ba15318d958d89384854c9c4ec449c24723d63a1c83e872dff85d15c530dd5db97e0dfd75a7284451

test:
  secret_key_base: d2426f9d29d85a2d30f4d6848333106e7905a2b80a7d92d5bb3c10677ccdaf6a469f2bcd9f36bdd8c2ac3730ce414579ca40fc0a03db807066e84b97c6a69f64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
